(load "~/clui/projects/clui/clui.asd")
(load "~/clui/projects/magical-skeleton/magical-skeleton.asd")
(ql:quickload :sb-introspect)
(ql:quickload :deploy)
(ql:quickload :magical-skeleton)
(in-package :magical-skeleton)
(setf clui::*outer-package* *package*)
(clui::update-outer-package-path)
(push :deploy-console *features*)
(deploy:define-resource-directory assets (clui::clui-assets-dir))
(deploy:define-resource-directory fonts (clui::clui-path "fonts/"))
(deploy:define-resource-directory magical-assets (clui::outer-package-assets-dir))
(asdf:make :magical-skeleton)